// KickStock shared ABI package
// Human-readable ABIs (viem / ethers compatible)

const MockUSDT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function faucet()",
  "function mint(address to, uint256 amount)",
  "function faucetAmount() view returns (uint256)",
  "function faucetCooldown() view returns (uint256)",
  "function lastFaucet(address user) view returns (uint256)",
  "function setFaucetConfig(uint256 amount, uint256 cooldown)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event Faucet(address indexed user, uint256 amount)",
  "event FaucetConfigUpdated(uint256 amount, uint256 cooldown)",
];

const PlayerToken_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function initialize(string name, string symbol, address market, address usdt)",
  "function market() view returns (address)",
  "function usdt() view returns (address)",
  "function accDivPerShare() view returns (uint256)",
  "function eligibleSupply() view returns (uint256)",
  "function rewardDebt(address account) view returns (uint256)",
  "function claimable(address account) view returns (uint256)",
  "function excluded(address account) view returns (bool)",
  "function mintShares(address to, uint256 amount)",
  "function burnShares(address from, uint256 amount)",
  "function accrue(uint256 amount)",
  "function claim()",
  "function pending(address account) view returns (uint256)",
  "function setExcluded(address account, bool status)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event DividendAccrued(uint256 amount, uint256 accDivPerShare)",
  "event DividendClaimed(address indexed account, uint256 amount)",
  "event ExcludedSet(address indexed account, bool status)",
];

const PlayerTokenFactory_ABI = [
  "function implementation() view returns (address)",
  "function createToken(uint256 playerId, string name, string symbol, address market, address usdt) returns (address)",
  "event TokenCreated(uint256 indexed playerId, address token)",
];

const PlayerMarket_ABI = [
  "function usdt() view returns (address)",
  "function factory() view returns (address)",
  "function curveBase() view returns (uint256)",
  "function curveSlope() view returns (uint256)",
  "function feeBps() view returns (uint16)",
  "function referralBps() view returns (uint16)",
  "function divShareBps() view returns (uint16)",
  "function oracle() view returns (address)",
  "function players(uint256 playerId) view returns (address token, uint256 supply, uint256 reserve, uint256 dividendBudget)",
  "function listedPlayerIds(uint256 index) view returns (uint256)",
  "function referrer(address user) view returns (address)",
  "function protocolFees() view returns (uint256)",
  "function listPlayer(uint256 playerId, string name, string symbol)",
  "function listPlayersBatch(uint256[] playerIds, string[] names, string[] symbols)",
  "function currentPrice(uint256 playerId) view returns (uint256)",
  "function quoteBuy(uint256 playerId, uint256 amount) view returns (uint256 totalCost, uint256 fee)",
  "function quoteSell(uint256 playerId, uint256 amount) view returns (uint256 netProceeds, uint256 fee)",
  "function buy(uint256 playerId, uint256 amount, uint256 maxCost)",
  "function sell(uint256 playerId, uint256 amount, uint256 minProceeds)",
  "function setReferrer(address ref)",
  "function distribute(uint256 playerId, uint8 statType, uint256 reward)",
  "function fundDividends(uint256 playerId, uint256 amount)",
  "function withdrawProtocolFees(address to)",
  "function setOracle(address oracle)",
  "function setCurveBase(uint256 base)",
  "function setCurveSlope(uint256 slope)",
  "function setFeeBps(uint16 bps)",
  "function setFeeWeights(uint16 referralBps, uint16 divShareBps)",
  "function listedCount() view returns (uint256)",
  "function getPlayerInfo(uint256 playerId) view returns (address token, uint256 supply, uint256 reserve, uint256 dividendBudget)",
  "function reserveOf(uint256 playerId) view returns (uint256)",
  "function owner() view returns (address)",
  "function graduated(uint256 playerId) view returns (bool)",
  "function playerAmm(uint256 playerId) view returns (address)",
  "function canGraduate(uint256 playerId) view returns (bool)",
  "function graduationProgress(uint256 playerId) view returns (uint256)",
  "function graduate(uint256 playerId)",
  "event PlayerListed(uint256 indexed playerId, address token, string name, string symbol)",
  "event Bought(uint256 indexed playerId, address indexed buyer, uint256 amount, uint256 cost, uint256 fee, uint256 newSupply)",
  "event Sold(uint256 indexed playerId, address indexed seller, uint256 amount, uint256 proceeds, uint256 fee, uint256 newSupply)",
  "event ReferralPaid(address indexed referrer, address indexed trader, uint256 amount)",
  "event DividendFunded(uint256 indexed playerId, uint256 amount)",
  "event DividendDistributed(uint256 indexed playerId, uint8 statType, uint256 amount)",
  "event ParamUpdated(string param, uint256 value)",
  "event OracleUpdated(address indexed oldOracle, address indexed newOracle)",
  "event ProtocolFeesWithdrawn(address indexed to, uint256 amount)",
  "event ReferrerSet(address indexed user, address indexed referrer)",
  "event Graduated(uint256 indexed playerId, address amm, uint256 usdtSeeded, uint256 tokensSeeded)",
];

const PlayerAMM_ABI = [
  "function usdt() view returns (address)",
  "function playerToken() view returns (address)",
  "function market() view returns (address)",
  "function reserveUsdt() view returns (uint256)",
  "function reserveToken() view returns (uint256)",
  "function initialized() view returns (bool)",
  "function protocolFeesUsdt() view returns (uint256)",
  "function price() view returns (uint256)",
  "function getK() view returns (uint256)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function initialize(address usdt, address token, address market, uint256 usdtAmount, uint256 tokenAmount)",
  "function addLiquidity(uint256 usdtAmount, uint256 minLp) returns (uint256 lpMinted)",
  "function removeLiquidity(uint256 lpAmount, uint256 minUsdt, uint256 minToken) returns (uint256 usdtOut, uint256 tokenOut)",
  "function swapUsdtForShares(uint256 usdtIn, uint256 minOut) returns (uint256 tokenOut)",
  "function swapSharesForUsdt(uint256 tokenIn, uint256 minOut) returns (uint256 usdtOut)",
  "function withdrawProtocolFees(address to)",
  "event Initialized(uint256 usdtAmount, uint256 tokenAmount, uint256 lpMinted)",
  "event LiquidityAdded(address indexed provider, uint256 usdtAmount, uint256 tokenAmount, uint256 lpMinted)",
  "event LiquidityRemoved(address indexed provider, uint256 usdtAmount, uint256 tokenAmount, uint256 lpBurned)",
  "event Swapped(address indexed trader, bool usdtIn, uint256 amountIn, uint256 amountOut, uint256 fee, uint256 newReserveUsdt, uint256 newReserveToken)",
  "event ProtocolFeesWithdrawn(address indexed to, uint256 amount)",
];

const PerformanceOracle_ABI = [
  "function market() view returns (address)",
  "function statReward(uint8 statType) view returns (uint256)",
  "function pushStat(uint256 playerId, uint8 statType)",
  "function pushBatch(uint256[] playerIds, uint8[] statTypes)",
  "function setStatReward(uint8 statType, uint256 reward)",
  "function setMarket(address market)",
  "function owner() view returns (address)",
  "event StatPushed(uint256 indexed playerId, uint8 statType, uint256 reward)",
  "event StatBatchPushed(uint256 count)",
  "event StatRewardUpdated(uint8 statType, uint256 reward)",
  "event MarketUpdated(address indexed oldMarket, address indexed newMarket)",
];

module.exports = {
  MockUSDT_ABI,
  PlayerToken_ABI,
  PlayerTokenFactory_ABI,
  PlayerMarket_ABI,
  PlayerAMM_ABI,
  PerformanceOracle_ABI,
};
